# We hardcode the version numbers since we cannot determine versions during
# configure stage.
if (BUILD_VTK7)
  set (vtk_version_major 7)
  set (vtk_version_minor 1)
  set (vtk_version_patch 1)
  #set (vtk_version_suffix "RC2")
else ()
  set (vtk_version_major 6)
  set (vtk_version_minor 3)
  set (vtk_version_patch 0)
  #set (vtk_version_suffix "RC1")
endif ()
set (vtk_version "${vtk_version_major}.${vtk_version_minor}")
if (vtk_version_suffix)
  set (vtk_version_long "${vtk_version}.${vtk_version_patch}-${vtk_version_suffix}")
  set (vtk_version_tag "${vtk_version}.${vtk_version_patch}.${vtk_version_suffix}")
else()
  set (vtk_version_long "${vtk_version}.${vtk_version_patch}")
  set (vtk_version_tag "${vtk_version}.${vtk_version_patch}")
endif()
